# Analiza podataka dobijenih simulacijom u SUMO-GUI okruzenju
## Import svih potrebnih biblioteka za analizu

In [1]:
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine

import movingpandas as mpd
from shapely.geometry import Point
import folium
import numpy as np

C:\D\GIS\GIS-GIT\GIS-GIT\Project 3\sumo_postgis\venv\Lib\site-packages\movingpandas\__init__.py:41: UserWarning: Missing optional dependencies. To use the trajectory smoother classes please install Stone Soup (see https://stonesoup.readthedocs.io/en/latest/#installation).
  warnings.warn(e.msg, UserWarning)

## Uspostavljanje konekcije sa PostGIS bazom podataka

In [2]:
engine = create_engine("postgresql://postgres:Petsre971$$$@localhost:5432/sumo_db")

## Uzimanje podataka ( vozila ) iz PostGIS baze podataka

In [3]:
fcd = gpd.read_postgis(
    """
    SELECT *
    FROM fcd_tracks
    """,
    engine,
    geom_col="geom"
)

#ovo sam napisao jer sam greskom oznacio geom podatke u POSTGIS pri importovanju podataka da su EPSG:3857
#umesto EPSG:4326 pa ispravljam gresku naknadno, plus konvertujem u EPSG:3857 jer je neophodno za analizu u ovom slucaju
fcd = fcd.set_crs(4326, allow_override=True).to_crs(3857)

#ispravljaju se i x/y kolone tako da budu u ispravnom koodrinatnom sistemu
fcd["x"] = fcd.geometry.x
fcd["y"] = fcd.geometry.y

print("FCD shape:", fcd.shape)
print("\nKolone:", fcd.columns)
print("\nPrvih 5 redova:")
display(fcd.head())

FCD shape: (1756660, 11)

Kolone: Index(['vehicle_id', 'time', 'x', 'y', 'angle', 'type', 'speed', 'pos', 'lane',
       'slope', 'geom'],
      dtype='str')

Prvih 5 redova:

,vehicle_id,time,x,y,angle,type,speed,pos,lane,slope,geom
0,bus0,0.0,478648.986165,6.816522e+06,335.41,bus_bus,8.33,12.10,7493814_0,0.0,POINT (478648.986 6816521.529)
1,motorcycle0,0.0,479878.509940,6.817127e+06,153.28,motorcycle_motorcycle,13.89,2.30,-200026251#2_0,0.0,POINT (479878.51 6817127.054)
2,truck0,0.0,479328.146378,6.817549e+06,130.27,truck_truck,8.46,7.20,-7475252_0,0.0,POINT (479328.146 6817549.246)
3,veh0,0.0,479826.746377,6.816928e+06,330.37,veh_passenger,13.89,5.10,7477284#0_0,0.0,POINT (479826.746 6816927.925)
4,bus0,1.0,478642.529634,6.816533e+06,330.31,bus_bus,8.22,20.32,7493814_0,0.0,POINT (478642.53 6816533.306)

## konverzija formata vremena iz sekundi u datetime, jer movingpandas radi sa datetime formatom

In [4]:
import datetime

base_time = pd.Timestamp("2026-01-01")

fcd["t"] = base_time + pd.to_timedelta(fcd["time"], unit="s")

#sada svi vremenski podaci su konvertovani iz sekunda u 2026-01-01 + offset (tj broj sekunda).

print("primer vremenske kolone:")
display(fcd[["time", "t"]].head())

print("vremenski opseg:")
print(fcd["t"].min(), "→", fcd["t"].max())

primer vremenske kolone:

   time                   t
0   0.0 2026-01-01 00:00:00
1   0.0 2026-01-01 00:00:00
2   0.0 2026-01-01 00:00:00
3   0.0 2026-01-01 00:00:00
4   1.0 2026-01-01 00:00:01

vremenski opseg:
2026-01-01 00:00:00 → 2026-01-01 00:59:59

# Analiza 1 : Ulice sa najgušćim saobraćajem u određenom vremenskom periodu

In [5]:
import branca.colormap as cm
from shapely.geometry import LineString

# Postavljanje ulaznih parametara ( vremenski period koji se gleda i uslov da je kroz ulicu proslo minimum N vozila

In [6]:
start_time = pd.Timestamp("2026-01-01 00:00:00")
end_time = pd.Timestamp("2026-01-01 01:00:00")

N = 20

print("Početak:", fcd["t"].min())
print("Kraj:  ", fcd["t"].max())

Početak: 2026-01-01 00:00:00
Kraj:   2026-01-01 00:59:59

## Filtriranje podataka, ostaju samo oni podaci koji su u navedenom vremenskom perioudu

In [7]:
period = fcd[
    (fcd["t"] >= start_time) &
    (fcd["t"] <= end_time)
].copy()

print("Koliko redova ima za dati uslov:", len(period))
print("Broj vozila za izabrani vremenski period:", period["vehicle_id"].nunique())
print()

Koliko redova ima za dati uslov: 1756660
Broj vozila za izabrani vremenski period: 2375

## Računa se broj (jedinstvenih) vozila po ulici odnosno segmentu ulice (lane)

In [8]:
#grupišemo podatke iz fcd po lane-ovima, zatim se fokusiramo na vehicle-id i izračunavamo broj jedinstvenih vozila po lane-u sa nunique()
#Sa reset index agregirane podatke čuvamo u dataframe u sa lane kolonom i kolonom koja se zove vehicle count ( broj vozila po lane-u )
traffic = (
    period.groupby("lane")["vehicle_id"]
    .nunique()
    .reset_index(name="vehicle_count")
)

#ovde se sortira dataframe tako da krećemo od lane-ova sa najviše vozila i završavamo sa lane-ovima sa najmanje vozila
traffic = traffic.sort_values(
    "vehicle_count",
    ascending=False
)

print("Top 10 ulica po broju vozila:")
print(traffic.head(10))
print()

Top 10 ulica po broju vozila:
                 lane  vehicle_count
0        -100871996_0            364
9       -1410066164_0            343
7     -1410066163#1_0            341
10      -1410066165_0            332
396   :1165729136_1_0            318
412   :1165729284_1_0            269
427  :12956562836_0_0            256
430  :12956562837_0_0            251
226      48095976#0_0            238
376     921068618#0_0            237

In [9]:
#iz prethodne tabele zatim čuvamo samo lane-ove koji zadovoljavaju lower bound broja vozila po lane-u
busy_lanes = traffic[
    traffic["vehicle_count"] > N
]

print(f"Lane-ovi sa više od {N} vozila:", len(busy_lanes))
print()

Lane-ovi sa više od 20 vozila: 573

# U ostatku analize point podaci se pretvaraju u line segmente ( zbog vizuelizacije )

In [10]:
lane_lines = []

#dakle prvo grupišemo podatke po lane-ovima, group je zaseban dataframe koji okuplja sve podatke za određeni lane
for lane, group in period.groupby("lane"):

    #sortiraju se podaci po (formatiranom) vremenu za dati lane
    group = group.sort_values("t")

    # iz x i y koordinata formiraju se uređeni parovi koji predstavljaju tačke geometrije
    coords = list(zip(group["x"], group["y"]))

    # uklanjaju se duplikati, jer simulirano vozilo može biti stacionarno ( parkirano ili je prosto stalo )
    coords = list(dict.fromkeys(coords))

    if len(coords) < 2:
        continue

    # od koordinata se formira jedan LineString koji predstavlja geometriju datog lane-a
    lane_lines.append({
        "lane": lane,
        "geometry": LineString(coords)
    })

#zatim se kreira novi geodataframe sa našim linestringovima
lane_gdf = gpd.GeoDataFrame(
    lane_lines,
    geometry="geometry",
    crs="EPSG:3857"
)

# ovde se merguju brojevi vozila po lane-u i lokacije odnosno novokreirane linije

In [11]:
# merge spaja geometrije lane-ova sa tabelom koja sadrži broj vozila,
# koristeći kolonu "lane" kao zajednički identifikator
result = lane_gdf.merge(busy_lanes, on="lane")

print("broj linestringova:", len(result))
print()

broj linestringova: 573

In [12]:
print("Geometrijski tipovi:")
print(result.geometry.geom_type.value_counts())
print()

print("statisika o vozilima:")
print(result["vehicle_count"].describe())
print()

print("top 10 linestringova po broju vozila:")
print(result[["lane", "vehicle_count"]]
      .sort_values("vehicle_count", ascending=False)
      .head(10))

Geometrijski tipovi:
LineString    573
Name: count, dtype: int64

statisika o vozilima:
count    573.000000
mean      77.366492
std       56.822922
min       21.000000
25%       35.000000
50%       57.000000
75%      106.000000
max      364.000000
Name: vehicle_count, dtype: float64

top 10 linestringova po broju vozila:
                 lane  vehicle_count
0        -100871996_0            364
5       -1410066164_0            343
4     -1410066163#1_0            341
6       -1410066165_0            332
289   :1165729136_1_0            318
294   :1165729284_1_0            269
300  :12956562836_0_0            256
303  :12956562837_0_0            251
165      48095976#0_0            238
280     921068618#0_0            237

# predstavljanje podataka pomoću folium mape

In [13]:
#prvo se reprojektusu podaci u EPSG:4326 jer folium koristi taj koordinatni sistem
result = result.to_crs(epsg=4326)

#uprošćava se geometrija jer u suprotnom je vizuelizacija veoma skupa operacija, čekao sam 5 minuta i mapa se još nije učitala
#sa uprošćavanjem mapa je mogla da se izračuna za 2 sekunde i da se renderuje.
result["geometry"] = result["geometry"].simplify(5)

# sve geometrije se objedinjuju u jednu celinu, zatim se računa njihov centroid,
# koji se koristi kao centar prikaza mape, tj inicijalna pozicija na mapi
center_geom = result.geometry.union_all().centroid

center = [center_geom.y, center_geom.x]
# sve ovo je odrađeno kako bi se pravilno pozicionirao view pri renderovanju.

#renderovanje mape sa centrom u 'center' promenljivu

m = folium.Map(
    location=center,
    zoom_start=13,
    tiles="CartoDB positron"
)

# definiše se kolor mapa gde minimalni i maksimalni broj vozila određuju opseg boja
colormap = cm.LinearColormap(
    colors=["yellow", "orange", "red"],
    vmin=result["vehicle_count"].min(),
    vmax=result["vehicle_count"].max()
)

# svaki lane se iscrtava kao PolyLine pri čemu boja zavisi od broja vozila

for _, row in result.iterrows():

    coords = list(row.geometry.coords)

    folium.PolyLine(
        locations=[(y, x) for x, y in coords],
        color=colormap(row["vehicle_count"]),
        weight=4,
        opacity=0.8,
        tooltip=f"Lane: {row['lane']} | Vehicles: {row['vehicle_count']}"
    ).add_to(m)

colormap.caption = "Vehicle Count per Lane"
colormap.add_to(m)


print("najveći broj vozila po lane-u:", result["vehicle_count"].max())
print("prosečan broj vozila:", round(result["vehicle_count"].mean(), 2))
print("minimalan broj vozila:", result["vehicle_count"].min())

m

najveći broj vozila po lane-u: 364
prosečan broj vozila: 77.37
minimalan broj vozila: 21