# Analiza podataka dobijenih simulacijom u SUMO-GUI okruzenju
## Import svih potrebnih biblioteka za analizu

In [1]:
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine

import movingpandas as mpd
from shapely.geometry import Point
import folium
import numpy as np

C:\D\GIS\GIS-GIT\GIS-GIT\Project 3\sumo_postgis\venv\Lib\site-packages\movingpandas\__init__.py:41: UserWarning: Missing optional dependencies. To use the trajectory smoother classes please install Stone Soup (see https://stonesoup.readthedocs.io/en/latest/#installation).
  warnings.warn(e.msg, UserWarning)

## Uspostavljanje konekcije sa PostGIS bazom podataka

In [ ]:
engine = create_engine("postgresql://postgres:password@localhost:5432/sumo_db")

## Uzimanje podataka ( emisije vozila ) iz PostGIS baze podataka

In [3]:
emissions = pd.read_sql(
    "SELECT * FROM vehicle_emissions",
    engine
)

print("Emissions shape:", emissions.shape)
display(emissions.head(5))

print("\nKolone:")
print(emissions.columns)

print("\nVrednosti koje nedostaju:")
print(emissions.isnull().sum())

Emissions shape: (1756660, 20)

,vehicle_id,time,type,lane,route,x,y,speed,pos,angle,waiting,CO2,CO,HC,NOx,PMx,fuel,electricity,noise,eclass
0,bus0,0.0,bus_bus,7493814_0,!bus0!var#1,4.299777,52.090588,8.33,12.10,335.41,0.0,8197.83,2.18,0.20,4.72,1.59,2634.44,0.0,71.88,HBEFA4/UBus_Std_gt15-18t_Euro-VI_A-C
1,motorcycle0,0.0,motorcycle_motorcycle,-200026251#2_0,!motorcycle0!var#1,4.310822,52.093930,13.89,2.30,153.28,0.0,1937.28,72.33,25.34,2.48,0.55,628.19,0.0,64.57,HBEFA4/MC_4S_gt250cc_preEuro
2,truck0,0.0,truck_truck,-7475252_0,!truck0!var#1,4.305878,52.096260,8.46,7.20,130.27,0.0,3099.12,1.14,0.10,2.08,1.56,996.01,0.0,71.97,HBEFA4/RT_le7.5t_Euro-VI_A-C
3,veh0,0.0,veh_passenger,7477284#0_0,!veh0!var#1,4.310357,52.092831,13.89,5.10,330.37,0.0,2058.86,8.20,0.06,0.76,0.40,667.46,0.0,64.57,HBEFA4/PC_petrol_Euro-4
4,bus0,1.0,bus_bus,7493814_0,!bus0!var#1,4.299719,52.090653,8.22,20.32,330.31,0.0,6363.53,1.96,0.19,4.58,1.57,2044.93,0.0,71.32,HBEFA4/UBus_Std_gt15-18t_Euro-VI_A-C

Kolone:
Index(['vehicle_id', 'time', 'type', 'lane', 'route', 'x', 'y', 'speed', 'pos',
       'angle', 'waiting', 'CO2', 'CO', 'HC', 'NOx', 'PMx', 'fuel',
       'electricity', 'noise', 'eclass'],
      dtype='str')

Vrednosti koje nedostaju:
vehicle_id     0
time           0
type           0
lane           0
route          0
x              0
y              0
speed          0
pos            0
angle          0
waiting        0
CO2            0
CO             0
HC             0
NOx            0
PMx            0
fuel           0
electricity    0
noise          0
eclass         0
dtype: int64

## konstrukcija geom polja u tabeli tj dataframe-u sa emisijama, markiranje u EPSG:4326 i konverzija u EPSG:3857 zbog analize

In [4]:
emissions["geometry"] = gpd.points_from_xy(emissions.x, emissions.y)

emissions = gpd.GeoDataFrame(
    emissions,
    geometry="geometry",
    crs="EPSG:4326"
)

#konverzija u EPSG:3857 zbog analize
emissions = emissions.to_crs(epsg=3857)

# x,y koordinate se konvertuju u EPSG:3857
emissions["x"] = emissions.geometry.x
emissions["y"] = emissions.geometry.y

print(emissions.crs)

print("Geometry type counts:")
print(emissions.geometry.geom_type.value_counts())

print("\nprimer geometrije:")
display(emissions.head())

EPSG:3857
Geometry type counts:
Point    1756660
Name: count, dtype: int64

primer geometrije:

,vehicle_id,time,type,lane,route,x,y,speed,pos,angle,...,CO2,CO,HC,NOx,PMx,fuel,electricity,noise,eclass,geometry
0,bus0,0.0,bus_bus,7493814_0,!bus0!var#1,478648.986165,6.816522e+06,8.33,12.10,335.41,...,8197.83,2.18,0.20,4.72,1.59,2634.44,0.0,71.88,HBEFA4/UBus_Std_gt15-18t_Euro-VI_A-C,POINT (478648.986 6816521.529)
1,motorcycle0,0.0,motorcycle_motorcycle,-200026251#2_0,!motorcycle0!var#1,479878.509940,6.817127e+06,13.89,2.30,153.28,...,1937.28,72.33,25.34,2.48,0.55,628.19,0.0,64.57,HBEFA4/MC_4S_gt250cc_preEuro,POINT (479878.51 6817127.054)
2,truck0,0.0,truck_truck,-7475252_0,!truck0!var#1,479328.146378,6.817549e+06,8.46,7.20,130.27,...,3099.12,1.14,0.10,2.08,1.56,996.01,0.0,71.97,HBEFA4/RT_le7.5t_Euro-VI_A-C,POINT (479328.146 6817549.246)
3,veh0,0.0,veh_passenger,7477284#0_0,!veh0!var#1,479826.746377,6.816928e+06,13.89,5.10,330.37,...,2058.86,8.20,0.06,0.76,0.40,667.46,0.0,64.57,HBEFA4/PC_petrol_Euro-4,POINT (479826.746 6816927.925)
4,bus0,1.0,bus_bus,7493814_0,!bus0!var#1,478642.529634,6.816533e+06,8.22,20.32,330.31,...,6363.53,1.96,0.19,4.58,1.57,2044.93,0.0,71.32,HBEFA4/UBus_Std_gt15-18t_Euro-VI_A-C,POINT (478642.53 6816533.306)

## konverzija formata vremena iz sekundi u datetime, jer movingpandas radi sa datetime formatom

In [5]:
import datetime

base_time = pd.Timestamp("2026-01-01")

emissions["t"] = base_time + pd.to_timedelta(emissions["time"], unit="s")

#sada svi vremenski podaci su konvertovani iz sekunda u 2026-01-01 + offset (tj broj sekunda).

print("Primer vremenske kolone:")
display(emissions[["time", "t"]].head())

print("vremenski opseg:")
print(emissions["t"].min(), "→", emissions["t"].max())

Primer vremenske kolone:

   time                   t
0   0.0 2026-01-01 00:00:00
1   0.0 2026-01-01 00:00:00
2   0.0 2026-01-01 00:00:00
3   0.0 2026-01-01 00:00:00
4   1.0 2026-01-01 00:00:01

vremenski opseg:
2026-01-01 00:00:00 → 2026-01-01 00:59:59

# Analiza 4 : Najzagađenije delove grada po vremenskim periodima

In [6]:
#analiziraćemo zagađenje (CO2 i NOx) tokom različitih vremenskih perioda

import numpy as np
from shapely.geometry import box
import folium

#bira se vremenski interval
START_TIME = pd.Timestamp("2026-01-01 00:00:00")
END_TIME   = pd.Timestamp("2026-01-01 01:00:00")

TIME_BIN   = "10min" # na svakih 10 minuta uzima se poseban snapshot, odnosno kao da faktički delimo naše podakte u delove od 10 minuta i analiziramo zagađenje za njih
CELL_SIZE  = 30  #veličina ćelije u metrima
# -----------------------------

#vrši se filtriranje emissions podataka po vremenu

emissions_f = emissions[
    (emissions["t"] >= START_TIME) &
    (emissions["t"] <= END_TIME)
].copy()

#u slučaju da nema nikakvih podataka baca grešku

if emissions_f.empty:
    raise ValueError("Za zadati vremenski prozor ne postoje podaci")

#ovde se vrši ta podela svih podataka u vremenske 'korpe' od po 10 minuta. npr svi podaci od 00:00:00 i 00:09:59 pripadaju jednoj korpi, i tako dalje
emissions_f["time_bin"] = emissions_f["t"].dt.floor(TIME_BIN)

#uklanjamo nepotrebne kolone jer zaista im ogroman broj podataka (750MB) pa ih uklanjamo jer nam ne trebaju ti podaci
emissions_f = emissions_f[["geometry", "time_bin", "CO2", "NOx"]]


#formira se rešetka tj. grid i uzimamo granične koordinate tj. bounds za naš skup podataka
xmin, ymin, xmax, ymax = emissions_f.total_bounds


#provera se da li su koordinate bounding box-a validne
if any(np.isnan([xmin, ymin, xmax, ymax])):
    raise ValueError("neke od vrednosti graničnih koordinata su nevalidne")


#ovde kreiramo listu koordinata na osnovu kojih ćemo da kreiramo kvadratiće koji pokrivaju ceo bounding box
x_coords = np.arange(xmin, xmax + CELL_SIZE, CELL_SIZE)
y_coords = np.arange(ymin, ymax + CELL_SIZE, CELL_SIZE)

#ovde zatim zapravo kreiramo ćelije tj kvadratiće koji će nam trebati kako bismo spojili emisije sa tim kvadratićima jer emisije su tačkice a svaka tačkica pripada nekom kvadratiću
#i tako će se kasnije sumirati i normalizovati
grid_cells = [
    box(x, y, x + CELL_SIZE, y + CELL_SIZE)
    for x in x_coords
    for y in y_coords
]

#ovde zatim naše prazne ćelije pretvaramo u GeoDataFrame
grid = gpd.GeoDataFrame({"geometry": grid_cells}, crs=emissions_f.crs)
#ovde našim ćelijama zatim dodeljujemo indekse tj id.
grid["grid_id"] = grid.index

#ovde pravimo prostorni spoj izmedju kvadratića koje smo kreirali i naših emisionih podataka za CO2 i NOx

joined = gpd.sjoin(emissions_f, grid, predicate="within", how="inner")

#naravno, proveravamo da li je prazno, jer ako je prazno nema potrebe išta da se vizuelizuje

if joined.empty:
    raise ValueError("Spatial join returned empty result")

#vršimo agregaciju tako što dodajemo svo zagađenje koje se dogodilo u nekom kvadratiću, i tako za svaki kvadratić

agg = joined.groupby(["grid_id", "time_bin"]).agg({
    "CO2": "sum",
    "NOx": "sum"
}).reset_index()


#zbog merge-ovanja izgubili smo geometriju te iz tog razloga moramo da vratimo našim grid_id-jevima svoje geometrije ( jer u suprotno imamo samo tabelu zagađenja ali bez ikakvog
#načina da spojimo te podatke sa kvadratićima koji služe za predstavljane zagađenja
agg = agg.merge(grid, on="grid_id")

#ponovo pretvaramo agg promenljivu u GeoDataFrame
agg = gpd.GeoDataFrame(agg, geometry="geometry", crs=emissions_f.crs)


#ovde selektujemo samo jedan time_bin odnosno vremenski isečak, u našem slučaju uzimamo prvi ali možemo bilo koji od 6 desetominutnih intervala u našoj simulaciji
t0 = agg["time_bin"].min()

#ovde iz našeg GeoDataFrame-a uzimamo samo podatke koji pripadaju prvom vremenskom isečku
slice_gdf = agg[agg["time_bin"] == t0].copy()

#kao i ranije, ako ne postoje podaci onda nema potrebe za vizuelizacijom, te se baca greška
if slice_gdf.empty:
    raise ValueError("Ne postoje podaci za ovaj vremenski isečak")

# nisam siguran zašto folium ne može da prihvati pandas timeframe ali nema veze, konvertujemo naš time_bin format u nešto što može da pročita folium
slice_gdf["time_bin"] = slice_gdf["time_bin"].astype(str)

#ovde sračunavamo indeks zagađenja (0.0 do 1.0), dakle normalizujemo vrednosti tako da idu od 0 do 1 i dali smo im određene težine tako da C02 utiče 60% na indeks a NOx 40%

slice_gdf["CO2_n"] = slice_gdf["CO2"] / (slice_gdf["CO2"].max() + 1e-9)
slice_gdf["NOx_n"] = slice_gdf["NOx"] / (slice_gdf["NOx"].max() + 1e-9)

slice_gdf["pollution_index"] = (
    0.6 * slice_gdf["CO2_n"] +
    0.4 * slice_gdf["NOx_n"]
)


#pošto nam je za vizualizaciju potreban EPSG:4326 koord sistem, konvertujemo podatke iz EPSG:3857 u EPSG:4326.

slice_gdf_4326 = slice_gdf.to_crs(4326)

# ovde računamo centar mape
centroid = slice_gdf_4326.geometry.union_all().centroid
center = [centroid.y, centroid.x]

#ovde kreiramo mapu u koju ubacujemo naše podatke ( centar mape i početni zoom )

m = folium.Map(location=center, zoom_start=14)

#imamo tri diskretne vrednosti koje boje će predstavljati naše podatke, plava, narandžasta i crvena.
def color(p):
    if p < 0.3:
        return "#2b83ba" #plava
    elif p < 0.6:
        return "#fdae61" #narandzasta
    else:
        return "#d7191c" #crvena

#boja i opacity se menja u zavisnosti od vrednosti indeksa zagađenja
def style_function(feature):
    val = feature["properties"]["pollution_index"]
    return {
        "fillColor": color(val),
        "color": "black",
        "weight": 0.3,
        "fillOpacity": 0.2 + val * 0.8
    }

folium.GeoJson(
    slice_gdf_4326,
    style_function=style_function,
    tooltip=folium.GeoJsonTooltip(
        fields=["grid_id", "CO2", "NOx", "pollution_index"],
        aliases=["Grid", "CO2", "NOx", "Pollution Index"]
    )
).add_to(m)

m